### ISSUE TITLE
App Install location patch

### ISSUE THREAD

**Issue by ghost** [MI-Global/MIUI.v7.Patches.Smali#1]
Hi, @Bormental !

I'm applying the app install patch on my ROMs, but it seems that even if I select SD card it doesn't work and tells me im outta space. Do you know what could be wrong?

**Comment by Lenovoved** [comment]
Most likely the application simply does not support installation on an external memory card. This function is only for supported applications. And to check whether the mount is properly done.

**Comment by Bormental** [comment]
Not every ROM supports changing install location. 
You can check it by adb command: `pm get-install-location`
and try to change with root by command `pm set-install-location X` where X is 0 (auto), 1 (internal), 2 (external).
That patch sets install location with this shell command.
